// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file call_frame.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_CALL_FRAME_H
#define BEACON_IL_CALL_FRAME_H
#include "../util/vector.h"

struct bc_Method;
struct bc_Constructor;
struct bc_OperatorOverload;
struct bc_GenericType;

typedef struct bc_CallFrame {
        struct bc_GenericType* Receiver;
        bc_Vector* Args;
        bc_Vector* TypeArgs;
} bc_CallFrame;

bc_CallFrame* bc_NewCallFrame(struct bc_GenericType* receiver, bc_Vector* args,
                              bc_Vector* type_args);

void bc_DeleteCallFrame(bc_CallFrame* self);
#endif