// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_print_layout.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_PRINT_LAYOUT_H
#define BEACON_IL_PRINT_LAYOUT_H
#include <stdbool.h>

/**
 * 指定の行番号を出力する必要がないならtrue.
 * @param lineno
 * @return
 */
bool bc_IsLineOfAlreadyILPrint(int lineno);

/**
 * 必要に応じて行番号を表示します.
 * @param lineno
 */
void bc_FormatILPrintLayout(int lineno);

/**
 * 行番号を表示しないならtrue.
 * @param is_hide
 */
void bc_HideILPrintLayout(bool is_hide);
#endif  // !SIGNAL_IL_PRINT_LAYOUT_H
