//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_return_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_STMT_RETURN_H
#define BEACON_IL_IL_STMT_RETURN_H
#include "../il_factor_interface.h"
#include "../il_stmt_interface.h"
struct bc_Enviroment;
/**
 * 値の返却を表す要素.
 */
typedef struct bc_ILReturn {
	bc_ILFactor* Factor;
} bc_ILReturn;

/**
 * 式を返却する文をスーパーセットにラップします.
 * @param self
 * @return
 */
bc_ILStatement* bc_WrapILReturn(bc_ILReturn* self);

/**
 * 式を返却する文を作成します.
 * @return
 */
bc_ILReturn* bc_NewILReturn();

/**
 * 式を返却する文を生成します.
 * @param self
 * @param env
 * @param cctx
 */
void bc_GenerateILReturn(bc_ILReturn* self, bc_Enviroment* env, bc_CallContext* cctx);

/**
 * 式を返却する文を読み込みます.
 * @param self
 * @param env
 * @param cctx
 */
void bc_LoadILReturn(bc_ILReturn* self, bc_Enviroment* env, bc_CallContext* cctx);

/**
 * 式を返却する文を開放します.
 * @param self
 */
void bc_DeleteILReturn(bc_ILReturn* self);
#endif // !SIGNAL_IL_IL_STMT_RETURN_H
