// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_yield_break_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_YIELD_BREAK_H
#define BEACON_IL_YIELD_BREAK_H
#include "../il_factor_interface.h"
#include "../il_stmt_interface.h"

void bc_GenerateILYieldBreak(ILStatementYieldBreak* self, bc_Enviroment* env,
                             bc_CallContext* cctx);

void bc_LoadILYieldBreak(ILStatementYieldBreak* self, bc_Enviroment* env,
                         bc_CallContext* cctx);
#endif