//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_break_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_STMT_BREAK_H
#define BEACON_IL_IL_STMT_BREAK_H
#include "../il_stmt_interface.h"

struct bc_Enviroment;

bc_ILStatement* bc_WrapILBreak();

void bc_GenerateILBreak(void* empty, bc_Enviroment* env, bc_CallContext* cctx);

void bc_LoadILBreak(void* empty, bc_Enviroment* env, bc_CallContext* cctx);

void bc_DeleteILBreak(void* empty);
#endif // !SIGNAL_IL_IL_STMT_BREAK_H
