//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_return_empty_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_STMT_RETURN_EMPTY_H
#define BEACON_IL_STMT_RETURN_EMPTY_H
#include "../il_stmt_interface.h"

/**
 * 式を返却する文を生成します.
 * @param self
 * @param env
 * @param cctx
 */
void bc_GenerateILReturnEmpty(ILReturnEmpty self, bc_Enviroment* env, bc_CallContext* cctx);

/**
 * 式を返却する文を読み込みます.
 * @param self
 * @param env
 * @param cctx
 */
void bc_LoadILReturnEmpty(ILReturnEmpty self, bc_Enviroment* env, bc_CallContext* cctx);
#endif