//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_assert_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_IL_STMT_ASSERT_H
#define BEACON_IL_IL_STMT_ASSERT_H
#include "../il_factor_interface.h"
#include "../il_stmt_interface.h"
struct bc_Enviroment;
struct ILStatement;

typedef struct ILAssert {
	ILFactor* Condition;
	ILFactor* Message;
	struct ILStatement* Parent;
} ILAssert;

ILStatement* WrapILAssert(ILAssert* self);

ILAssert* NewILAssert();

void GenerateILAssert(ILAssert* self, bc_Enviroment* env, CallContext* cctx);

void LoadILAssert(ILAssert* self, bc_Enviroment* env, CallContext* cctx);

void DeleteILAssert(ILAssert* self);
#endif