//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_inferenced_type_init_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_STMT_INFERENCED_TYPE_INIT
#define BEACON_IL_IL_STMT_INFERENCED_TYPE_INIT
#include "../il_factor_interface.h"
#include "../il_stmt_interface.h"
#include "../../util/string_pool.h"
struct bc_Enviroment;
struct bc_SymbolEntry;
/**
 * 推論された型の初期化を表す要素.
 * var y = new X::Y();
 */
typedef struct bc_ILInferencedTypeInit {
	bc_StringView Name;
	bc_ILFactor* Value;
	struct bc_SymbolEntry* Symbol;
} bc_ILInferencedTypeInit;

/**
 * 推論された型の初期化を表す要素をスーパーセットにラップします.
 * @param self
 * @return
 */
bc_ILStatement* bc_WrapILInferencedTypeInit(bc_ILInferencedTypeInit* self);

/**
 * 推論された型の初期化を表す要素を作成します.
 * @param namev
 * @return
 */
bc_ILInferencedTypeInit* bc_NewILInferencedTypeInit(bc_StringView namev);

/**
 * 推論された型の初期化を表す要素を生成します.
 * @param self
 * @param env
 * @param cctx
 */
void bc_GenerateILInferencedTypeInit(bc_ILInferencedTypeInit* self, bc_Enviroment* env, bc_CallContext* cctx);

/**
 * 推論された型の初期化を表す要素を読み込みます.
 * @param self
 * @param env
 * @param cctx
 */
void bc_LoadILInferencedTypeInit(bc_ILInferencedTypeInit* self, bc_Enviroment* env, bc_CallContext* cctx);

/**
 * 推論された型の初期化を表す要素を開放します.
 * @param self
 */
void bc_DeleteILInferencedTypeInit(bc_ILInferencedTypeInit* self);
#endif // !SIGNAL_IL_IL_STMT_INFERENCED_TYPE_INIT
