//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_while_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_STMT_WHILE_H
#define BEACON_IL_IL_STMT_WHILE_H
#include "../il_factor_interface.h"
#include "../il_stmt_interface.h"
#include "../../util/vector.h"

struct bc_Enviroment;

typedef struct bc_ILWhile {
	bc_ILFactor* Condition;
	bc_Vector* Statements;
} bc_ILWhile;

bc_ILStatement* bc_WrapILWhile(bc_ILWhile* self);

bc_ILWhile* bc_NewILWhile();

void bc_GenerateILWhile(bc_ILWhile* self, bc_Enviroment* env, bc_CallContext* cctx);

void bc_LoadILWhile(bc_ILWhile* self, bc_Enviroment* env, bc_CallContext* cctx);

void bc_DeleteILWhile(bc_ILWhile* self);
#endif // !SIGNAL_IL_IL_STMT_WHILE_H
