//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_throw_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_IL_STM_THROW_H
#define BEACON_IL_IL_STM_THROW_H
#include "../il_factor_interface.h"
#include "../il_stmt_interface.h"

struct Enviroment;

typedef struct ILThrow {
	ILFactor* Factor;
} ILThrow;

ILStatement* WrapILThrow(ILThrow* self);

ILThrow* NewILThrow();

void GenerateILThrow(ILThrow* self, Enviroment* env, CallContext* cctx);

void LoadILThrow(ILThrow* self, Enviroment* env, CallContext* cctx);

void DeleteILThrow(ILThrow* self);
#endif
