//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_bool.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SIGNAL_LANG_BOOL_H
#define BEACON_LIB_SIGNAL_LANG_BOOL_H
#include "../../bc_library_impl.h"
struct Type;

/**
 * 真偽値を表すオブジェクトです。
 */
typedef struct Bool {
	Object Super;
	bool Value;
} Bool;

/**
 * 新しい真偽値オブジェクトを生成します。
 * @param value
 * @return
 */
Bool* NewBool(bool value);

/**
 * beacon::lang::Boolクラスを初期化します.
 */
void InitBCBool();

/**
 * beacon::lang::Bool型を返します.
 * @return
 */
struct Type* GetBCBoolType();
#endif // !SIGNAL_LIB_SIGNAL_LANG_BOOL_H
