//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_char.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SIGNAL_LANG_CHAR_H
#define BEACON_LIB_SIGNAL_LANG_CHAR_H
struct Type;
/**
 * beacon::lang::Charクラスを初期化します.
 */
void InitBCChar();

/**
 * beacon::lang::Char型を返します.
 * @return
 */
struct Type* GetBCCharType();
#endif // !SIGNAL_LIB_SIGNAL_LANG_CHAR_H
