//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_char.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SIGNAL_LANG_CHAR_H
#define BEACON_LIB_SIGNAL_LANG_CHAR_H
#include "../../bc_library_impl.h"
/**
 * 文字を表すデータ型です。
 */
typedef struct Char {
	bc_Object Super;
	char Value;
} Char;
struct bc_Type;

/**
 * 新しい文字オブジェクトを生成します。
 * @param value
 * @return
 */
struct bc_Object* NewChar(char value);

/**
 * beacon::lang::Charクラスを初期化します.
 */
void InitChar();

/**
 * beacon::lang::Char型を返します.
 * @return
 */
struct bc_Type* GetCharType();
#endif // !SIGNAL_LIB_SIGNAL_LANG_CHAR_H
