//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_int.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SIGNAL_LANG_INT_H
#define BEACON_LIB_SIGNAL_LANG_INT_H
#include "../../bc_library_impl.h"
struct bc_Type;
/**
 * 整数型のデータを表すオブジェクトです。
 */
typedef struct Integer {
	bc_Object Super;
	int Value;
} Integer;

/**
 * 新しい整数オブジェクトを生成します。
 * @param value
 * @return
 */
struct bc_Object* NewInteger(int value);

/**
 * beacon::lang::Intクラスを初期化します.
 */
void InitInt();

/**
 * beacon::lang::Intを返します.
 * @return
 */
struct bc_Type* GetIntType();
#endif // !SIGNAL_LIB_SIGNAL_LANG_INT_H
