//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_int.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SIGNAL_LANG_INT_H
#define BEACON_LIB_SIGNAL_LANG_INT_H
struct Type;
/**
 * beacon::lang::Intクラスを初期化します.
 */
void InitBCInt();

/**
 * beacon::lang::Intを返します.
 * @return
 */
struct Type* GetBCIntType();
#endif // !SIGNAL_LIB_SIGNAL_LANG_INT_H
