//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_long.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/11/4
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_LIB_BEACON_LANG_H
#define BEACON_LIB_BEACON_LANG_H
#include "../../bc_library_impl.h"

/**
 * 64bit整数を扱うオブジェクトです。
 */
typedef struct Long {
	Object Super;
	long Value;
} Long;

/**
 * 64bit整数を返します。
 * @param value
 * @return
 */
struct Object* NewLong(long value);
#endif