//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_long.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/11/4
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_LIB_BEACON_LANG_H
#define BEACON_LIB_BEACON_LANG_H
#include "../../bc_library_impl.h"

/**
 * 64bit整数を扱うオブジェクトです。
 */
typedef struct bc_Long {
	bc_Object Super;
	long Value;
} bc_Long;

/**
 * 64bit整数を返します。
 * @param value
 * @return
 */
struct bc_Object* bc_NewLong(long value);

/**
 * beacon::lang::Longクラスを初期化します.
 */
void bc_InitLong();

/**
 * beacon::lang::Intを返します.
 * @return
 */
struct bc_Type* bc_GetLongType();
#endif