//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file null.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SIGNAL_LANG_NULL_H
#define BEACON_LIB_SIGNAL_LANG_NULL_H
struct bc_Type;
/**
 * beacon::lang::Nullクラスを初期化します.
 */
void bc_InitNull();

/**
 * beacon::lang::Null型を返します.
 * @return
 */
struct bc_Type* bc_GetNullType();
#endif // !SIGNAL_LIB_SIGNAL_LANG_NULL_H
