//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file object.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SIGNAL_LANG_H
#define BEACON_LIB_SIGNAL_LANG_H
struct bc_Type;
/**
 * beacon::lang::Objectクラスを初期化します.
 */
void bc_InitObject();

/**
 * beacon::lang::Object型を返します.
 */
struct bc_Type* bc_GetObjectType();
#endif // !SIGNAL_LIB_SIGNAL_LANG_H
