// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file access_level.h
 * @brief メンバーのアクセスレベルを定義します。
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_AST_ACCESS_LEVEL_H
#define BEACON_AST_ACCESS_LEVEL_H
#include <stdbool.h>
/**
 * アクセスレベルを定義する列挙型.
 */
typedef enum bc_AccessLevel {
        ACCESS_PUBLIC_T = 0,
        ACCESS_PROTECTED_T,
        ACCESS_PRIVATE_T,
} bc_AccessLevel;

/**
 * @param self
 * @param other
 * @return selfがotherよりも脆弱なアクセスレベルならtrue
 */
bool bc_IsWeakAccess(bc_AccessLevel self, bc_AccessLevel other);
#endif  // !SIGNAL_AST_ACCESS_LEVEL_H
