// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bool.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SIGNAL_LANG_BOOL_H
#define BEACON_LIB_SIGNAL_LANG_BOOL_H
#include "../../bc_library_impl.h"
struct bc_Type;

/**
 * 真偽値を表すオブジェクトです。
 */
typedef struct bc_Bool {
        bc_Object Super;
        bool Value;
} bc_Bool;

/**
 * 新しい真偽値オブジェクトを生成します。
 * @param sctx
 * @param value
 * @return
 */
struct bc_Object* bc_NewBool(struct bc_ScriptContext* sctx, bool value);

/**
 * beacon::lang::Boolクラスを初期化します.
 */
void bc_InitBool();

/**
 * beacon::lang::Bool型を返します.
 * @param sctx
 * @return
 */
struct bc_Type* bc_GetBoolType(struct bc_ScriptContext* sctx);
#endif  // !SIGNAL_LIB_SIGNAL_LANG_BOOL_H
