// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file void.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SIGNAL_LANG_VOID_H
#define BEACON_LIB_SIGNAL_LANG_VOID_H
struct bc_Type;
/**
 * beacon::lang::Voidクラスを初期化します.
 */
void bc_InitVoid();

/**
 * beacon::lang::Void型を返します.
 * @return
 */
struct bc_Type* bc_GetVoidType();
#endif  // !SIGNAL_LIB_SIGNAL_LANG_VOID_H
