require "open3"
require "fileutils"
require "date"
#挿入するテキストのテンプレート
template = <<'EOS'
//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file FILE
 * @brief BRIEF
 * @author AUTHOR
 * @date DATE
 */
//END-AUTOGENERATED-BLOCK

EOS

def find_line(source, t)
    source.lines.each_with_index do |line, i|
        if line.include?(t) then
            return i
        end
    end
    return -1
end

Dir.glob("**/*") do |file|
    next if (!file.end_with?(".h"))
    #最初に全て読み込む
    content = nil
    File.open(file, "r") {|fp| content = fp.read}
    #すでに生成されている
    if(content.include?("BEGIN-AUTOGENERATED-BLOCK") &&
       content.include?("END-AUTOGENERATED-BLOCK")) then
        next
    end
    fixedContent = (template
        .gsub("FILE", File.basename(file))
        .gsub("BRIEF", "ここに概要を記述します")
        .gsub("AUTHOR", "koya")
        .gsub("DATE", "2018/10/31") + content)
    File.open(file, "w") {|fp| fp.write(fixedContent)}
end