//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file content_type.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_ENV_CONTEN_TYPE_H
#define BEACON_ENV_CONTEN_TYPE_H
/**
 * クラスローダーによって読み込まれるコンテンツの種類を表す列挙型.
 */
typedef enum ContentType {
	CONTENT_ENTRY_POINT_T,
	CONTENT_LIB_T
} ContentType;
#endif // !SIGNAL_ENV_CONTEN_TYPE_H
