// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file import_info.h
 * @brief インポートの1エントリあたりの情報を定義します。
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_ENV_IMPORT_INFO_H
#define BEACON_ENV_IMPORT_INFO_H
#include <stdbool.h>
struct bc_ClassLoader;

/**
 * インポート先のクラスローダーを格納します。
 */
typedef struct bc_ImportInfo {
        struct bc_ClassLoader* Context;
        bool IsConsume;
} bc_ImportInfo;

/**
 * 新しいインポートインフォを生成します。
 * @return
 */
bc_ImportInfo* bc_NewImportInfo();

/**
 * インポートインフォを解放します。
 * @param self
 */
void bc_DeleteImportInfo(bc_ImportInfo* self);
#endif  // !SIGNAL_ENV_IMPORT_INFO_H
