// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file link_type.h
 * @brief クラスローダーのリンク方法を定義します。
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#ifndef BEACON_ENV_LINK_TYPE_H
#define BEACON_ENV_LINK_TYPE_H
/**
 * クラスローダーの現在のリンク状態.
 */
typedef enum bc_LinkType {
        LINK_DECL_T,
        LINK_IMPL_T,
        LINK_NONE_T,
} bc_LinkType;
#endif