// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file method.h
 * @brief メソッドを定義します。
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK
#ifndef BEACON_ENV_MEMBER_H
#define BEACON_ENV_MEMBER_H
#include "../ast/access_level.h"
#include "../ast/modifier_type.h"

struct bc_Type;

/**
 * メンバーを表す構造体。
 */
typedef struct bc_Member {
        struct bc_Type* Parent;
        bc_AccessLevel Access;
        bc_ModifierType Modifier;
} bc_Member;

#define BC_MEMBER_TYPE(v) (((bc_Member*)v)->Parent)
#define BC_MEMBER_ACCESS(v) (((bc_Member*)v)->Access)
#define BC_MEMBER_MODIFIER(v) (((bc_Member*)v)->Modifier)

/**
 * 全ての値を初期化します。
 * @param self
 */
void bc_InitMember(bc_Member* self);
#endif