//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file native_method.h
 * @brief C言語で実行されるメソッドを定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_ENV_NATIVE_METHOD_H
#define BEACON_ENV_NATIVE_METHOD_H
struct NativeMethodRef;
struct Enviroment;
struct Method;
struct Frame;
/**
 * Cで実装されたメソッド.
 */
typedef struct NativeMethod {
	struct NativeMethodRef* Ref;
} NativeMethod;

/**
 * ネイティブメソッドを作成します.
 * @return
 */
NativeMethod* NewNativeMethod();

/**
 * ネイティブメソッドを実行します.
 * @param self
 * @param fr
 * @param env
 */
void ExecuteNativeMethod(NativeMethod* self, struct Method* parent, struct Frame* fr, struct Enviroment* env);

/**
 * ネイティブメソッドを開放します.
 * @param self
 */
void DeleteNativeMethod(NativeMethod* self);

#endif // !SIGNAL_ENV_NATIVE_METHOD_H
