//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file object.h
 * @brief beaconで使用されるあらゆるオブジェクトを定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_ENV_OBJECT_H
#define BEACON_ENV_OBJECT_H
#include "../util/vector.h"
#include <stdbool.h>

#define OBJ2INT(a) (ObjectToInt(a))
#define OBJ2DOUBLE(a) (ObjectToDouble(a))
#define OBJ2BOOL(a) (ObjectToBool(a))
#define OBJ2CHAR(a) (ObjectToChar(a))
#define OBJ2LONG(a) (ObjectToLong(a))

#define INT2OBJ(a) (IntToObject(a))
#define DOUBLE2OBJ(a) (DoubleToObject(a))
#define BOOL2OBJ(a) (BoolToObject(a))
#define CHAR2OBJ(a) (CharToObject(a))
#define LONG2OBJ(a) (LongToObject(a))

struct GenericType;
struct VTable;
/** 
 * オブジェクトの着色状態.
 * インクリメンタルGCのためのフラグです。
 */
typedef enum ObjectPaint {
	PAINT_UNMARKED_T,
	PAINT_MARKED_T,
	//コンテキストが終了するまで
	//GCの対象にならない
	//ソースコード中に直接記述されたリテラルのためのフラグ。
	PAINT_ONEXIT_T,
//	paint_white,
//	paint_black,
//	paint_gray
} ObjectPaint ;

/**
 * オブジェクトの種類を表す列挙.
 */
typedef enum ObjectTag {
	OBJECT_INT_T,
	OBJECT_LONG_T, //bc_timeでだけ使ってる
	OBJECT_DOUBLE_T,
	OBJECT_CHAR_T,
	OBJECT_STRING_T,
	OBJECT_BOOL_T,
	OBJECT_REF_T,
	OBJECT_ARRAY_T,
	OBJECT_NULL_T,
} ObjectTag;

/**
 * オブジェクトに対して送信することができる命令です。
 * これを判別することで一つの関数ポインタで処理を分岐させ、
 * オブジェクトひとつあたりのサイズを削減します。
 */
typedef int ObjectMessage;

/**
 * メッセージの引数です。
 */
typedef union ObjectMessageArgument {
	int Int;
	void* Any;
} ObjectMessageArgument;

/**
 * 全てのオブジェクトがサポートする必要のあるメッセージです。
 */
typedef enum StandardObjectMessage {
	OBJECT_MSG_NONE = 0,
	OBJECT_MSG_PRINT,
	OBJECT_MSG_DELETE,
	OBJECT_MSG_DESTROY,
	OBJECT_MSG_MARKALL,
	OBJECT_MSG_CLONE,
	OBJECT_MSG_GENERIC,
	OBJECT_MSG_END,
} StandardObjectMessage;

/**
 * ヒープに関連付けされるオブジェクト.
 * beacon で使用される全てのデータはこれ。
 */
typedef struct Object {
	struct GenericType* GType;
	struct VTable* VPtr;
	ObjectPaint Paint;
	ObjectTag Tag;
	Vector* Fields;
	Vector* NativeSlotVec;
	bool IsCoroutine;
	bool IsClone;
	void* (*OnMessage)(struct Object* self, ObjectMessage msg, int argc, ObjectMessageArgument argv[]);
} Object;

/**
 * 標準的なメッセージハンドラです。
 * 拡張メッセージハンドラを実装する場合はこれをラップするのが簡単です。
 * @param self
 * @param msg
 * @param argc
 * @param argv
 * @return
 */
void* HandleObjectMessage(Object* self, ObjectMessage msg, int argc, ObjectMessageArgument argv[]);

/**
 * 指定のサイズのメモリを確保して、ヒープに紐づけます。
 * @param object_size
 * @return
 */
void* NewObject(size_t object_size);

/**
 * オブジェクトを生成して型を割り当てます。
 * @param object_size
 * @param gtype
 * @return
 */
void* ConstructObject(size_t object_size, struct GenericType* gtype);

/**
 * 整数型のオブジェクトを作成します.
 * @param i
 * @return
 */
//#define Object_int_new(i) (MallocIntObject(i, __FILE__, __LINE__))
//Object* MallocIntObject(int i, const char* filename, int lineno);

/**
 * 可能ならキャッシュを返します.
 * @param i
 * @return
 */
Object* GetIntObject(int i);

/**
 * 浮動小数型のオブジェクトを作成します.
 * @param d
 * @return
 */
//#define Object_double_new(d) (MallocDoubleObject(d, __FILE__, __LINE__))
//Object* MallocDoubleObject(double d, const char* filename, int lineno);

/**
 * long型の値を作成します.
 * @param l
 * @return
 */
//#define Object_long_new(l) (MallocLongObject(l, __FILE__, __LINE__))
//Object* MallocLongObject(long l, const char* filename, int lineno);

/**
 * 文字型のオブジェクトを作成します.
 * @param c
 * @return
 */
//#define Object_char_new(c) (MallocCharObject(c, __FILE__, __LINE__))
//Object* MallocCharObject(char c, const char* filename, int lineno);

/**
 * 文字列型のオブジェクトを作成します.
 * @param s
 * @return
 */
//#define Object_string_new(s) (MallocStringObject(s, __FILE__, __LINE__))
//Object* MallocStringObject(const char* s, const char* filename, int lineno);

/**
 * 参照型のオブジェクトを作成します.
 * @return
 */
//#define Object_ref_new() (MallocRefObject(__FILE__, __LINE__))
//Object* MallocRefObject(const char* filename, int lineno);

/**
 * 真偽値型の値を参照します.
 * @param b
 * @return
 */
Object* GetBoolObject(bool b);

/**
 * trueを参照します.
 * @return
 */
Object* GetTrueObject();

/**
 * falseを参照します.
 * @return
 */
Object* GetFalseObject();

/**
 * nullを参照します.
 * @return
 */
Object* GetNullObject();

/**
 * このオブジェクトを複製します.
 * int/double/char/boolでのみ使用可能です。
 * @param self
 * @return
 */
Object* CopyObject(Object* self);

/**
 * 参照としてオブジェクトを複製します.
 * @param self
 * @return
 */
Object* CloneObject(Object* self);

/**
 * このオブジェクトと
 * このオブジェクトから参照可能なオブジェクトを全てマークします.
 * @param self
 * @param paint
 */
void PaintAllObject(Object* self, ObjectPaint paint);

/**
 * このオブジェクトと
 * このオブジェクトから参照可能なオブジェクトを全てマークします.
 * @param self
 */
void MarkAllObject(Object* self);

/**
 * まだ開放されていないオブジェクトの数を返します.
 * @return
 */
int CountActiveObject();

/**
 * オブジェクトの詳細を出力します.
 * @param self
 */
void PrintObject(Object* self);

/**
 * オブジェクトを開放します.
 * @param self
 */
void DeleteObject(Object* self);

/**
 * 定数などを解放するための関数.
 * @param self
 */
void DestroyObject(Object* self);

/**
 * beaconからCの int へ変換します.
 * @param self
 * @return
 */
int ObjectToInt(Object* self);

/**
 * beaconからCの double へ変換します.
 * @param self
 * @return
 */
double ObjectToDouble(Object* self);

/**
 * beaconからCの bool へ変換します.
 * @param self
 * @return
 */
bool ObjectToBool(Object* self);

/**
 * beaconからCの char へ変換します.
 * @param self
 * @return
 */
char ObjectToChar(Object* self);

/**
 * beaconからCの long へ変換します.
 * @param self
 * @return
 */
long ObjectToLong(Object* self);

/**
 * Cからbeaconの Int へ変換します.
 * @param i
 * @return
 */
Object* IntToObject(int i);

/**
 * Cからbeaconの Double へ変換します.
 * @param d
 * @return
 */
Object* DoubleToObject(double d);

/**
 * Cからbeaconの bool へ変換します.
 * @param b
 * @return
 */
Object* BoolToObject(bool b);

/**
 * Cからbeaconの char へ変換します.
 * @param c
 * @return
 */
Object* CharToObject(char c);

/**
 * Cからbeacon
 * @param l
 * @return
 */
Object* LongToObject(long l);

/**
 * 指定の型のデフォルト値を返します.
 * @param gt
 * @return
 */
Object* GetDefaultObject(struct GenericType* gt);

/**
 * このオブジェクトのデバッグ表現を返します.
 * @param self
 * @return
 */
const char* GetObjectName(Object* self);

/**
 * オブジェクトが文字型の値を持つなら true.
 * @param self
 * @return
 */
bool IsCharValue(Object* self);

/**
 * オブジェクトが真偽値型の値を持つなら true.
 * @param self
 * @return
 */
bool IsBoolValue(Object* self);

/**
 * オブジェクトが整数型の値を持つなら true.
 * @param self
 * @return
 */
bool IsIntValue(Object* self);

/**
 * オブジェクトが実数型の値を持つなら true.
 * @param self
 * @return
 */
bool IsDoubleValue(Object* self);

/**
 * オブジェクトが文字列型の値を持つなら true.
 * @param self
 * @return
 */
bool IsStringValue(Object* self);

/**
 * オブジェクトが空なら true.
 * @param self
 * @return
 */
bool IsNullValue(Object* self);
#endif // !SIGNAL_ENV_OBJECT_H
