//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file script_method.h
 * @brief beacon言語自体によって実行されるメソッドを定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_ENV_SCRIPT_METHOD_H
#define BEACON_ENV_SCRIPT_METHOD_H
#include "../util/vector.h"
#include "../vm/enviroment.h"
struct bc_Frame;
struct bc_Method;
struct bc_Enviroment;

/**
 * スクリプトで実装されたメソッド.
 */
typedef struct bc_ScriptMethod {
	bc_Enviroment* Env;
} bc_ScriptMethod;

/**
 * スクリプトで実装されたメソッドを作成します.
 * @return
 */
bc_ScriptMethod* bc_NewScriptMethod();

/**
 * メソッドを実行します.
 * @param self
 * @param parent
 * @param fr
 * @param env
 */
void bc_ExecuteScriptMethod(bc_ScriptMethod* self, struct bc_Method* parent, struct bc_Frame* fr, bc_Enviroment* env);

/**
 * メソッドを開放します.
 * @param self
 */
void bc_DeleteScriptMethod(bc_ScriptMethod* self);
#endif // !SIGNAL_ENV_SCRIPT_METHOD_H
