//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file type_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_ENV_TYPE_IMPL_H
#define BEACON_ENV_TYPE_IMPL_H

#include "type/class_impl.h"
#include "type/interface_impl.h"
#endif // !SIGNAL_ENV_TYPE_IMPL_H
