//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file vtable.h
 * @brief 仮想関数テーブルを定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_ENV_VTABLE_H
#define BEACON_ENV_VTABLE_H
#include "../util/vector.h"
struct bc_Method;
struct CallContext;
/**
 * メソッドの一覧をフラットに格納する配列です.
 * 同じシグネチャのメソッドが複数現れる場合には、
 * 親クラスで現れた時点の添え字をサブクラスの実装で上書きします。
 */
typedef struct bc_VTable {
	//恐らくアップキャストのときに必要
	struct bc_VTable* Parent;
	Vector* Elements;
} bc_VTable;

/**
 * VTableを作成します.
 * @return
 */
bc_VTable* bc_NewVTable();

/**
 * src の中身を dst へ複製します.
 * @param src
 * @param dst
 */
void bc_CopyVTable(bc_VTable* src, bc_VTable* dst);

/**
 * メソッド一覧に m を追加します.
 * 重複は検査されません。
 * 静的メソッドの場合は無視されます。
 * @param self
 * @param m
 */
void bc_AddVTable(bc_VTable* self, struct bc_Method* m);

/**
 * メソッド一覧に m を追加します.
 * 重複する場合には上書きします。
 * 静的メソッドの場合は無視されます。
 * @param self
 * @param m
 * @param cctx
 */
void bc_ReplaceVTable(bc_VTable* self, struct bc_Method* m, struct CallContext* cctx);

/**
 * VTableを開放します.
 * @param self
 */
void bc_DeleteVTable(bc_VTable* self);
#endif // !SIGNAL_ENV_VTABLE_H
