// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_defer_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_IL_STMT_DEFER_IMPL_H
#define BEACON_IL_IL_STMT_DEFER_IMPL_H
#include "../il_stmt_interface.h"

typedef struct bc_ILDefer {
        bc_ILStatement* Task;
} bc_ILDefer;

bc_ILStatement* bc_WrapILDefer(bc_ILDefer* self);

bc_ILDefer* bc_NewILDefer();

void bc_LoadILDefer(bc_ILDefer* self, bc_Enviroment* env, bc_CallContext* cctx);

void bc_GenerateILDefer(bc_ILDefer* self, bc_Enviroment* env,
                        bc_CallContext* cctx);

void bc_DeleteILDefer(bc_ILDefer* self);
#endif