//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_variable_static_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_IL_FACTOR_VARIABLE_STATIC_H
#define BEACON_IL_IL_FACTOR_VARIABLE_STATIC_H
#include "../../../env/fqcn_cache.h"
#include "../../il_factor_interface.h"
struct Enviroment;
struct bc_GenericType;

typedef struct ILVariableStatic {
	bc_FQCNCache* FQCN;
	Vector* TypeArgs;
} ILVariableStatic;

ILVariableStatic* NewILVariableStatic();

void GenerateILVariableStatic(ILVariableStatic* self, Enviroment* env, CallContext* cctx);

void LoadILVariableStatic(ILVariableStatic * self, Enviroment * env, CallContext* cctx);

struct bc_GenericType* EvalILVariableStatic(ILVariableStatic * self, Enviroment * env, CallContext* cctx);

char* ILVariableStaticToString(ILVariableStatic * self, Enviroment * env);

void DeleteILVariableStatic(ILVariableStatic* self);
#endif