// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file thread.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_THREAD_THREAD_H
#define BEACON_THREAD_THREAD_H
//#include "../util/stack.h"
#include <stdbool.h>
#include "../util/vector.h"
struct bc_ScriptContext;
struct bc_Frame;
struct bc_CallContext;
/**
 * 並列実行のための構造体です.
 * 現在の呼び出し位置を表すトレースのスタックを含みます。
 */
typedef struct bc_ScriptThread {
        bc_Vector* TraceStack;
        bool IsVMCrushByException;
        bool IsVMDump;
        struct bc_Frame* FrameRef;
        struct bc_CallContext* CCtx;
} bc_ScriptThread;

/**
 * メインスレッドを作成します.
 */
void bc_LaunchScriptThread();

/**
 * 新しいスレッドを作成します.
 * @return
 */
bc_ScriptThread* bc_NewScriptThread();

/**
 * 現在のスレッドを返します.
 * @param sctx
 * @return
 */
bc_ScriptThread* bc_GetCurrentScriptThread(struct bc_ScriptContext* sctx);

/**
 * スレッドに記録された全てのトレースを解放します.
 * @param self
 */
void bc_ClearScriptThread(bc_ScriptThread* self);

/**
 * スレッドを解放します.
 * @param self
 */
void bc_DeleteScriptThread(bc_ScriptThread* self);

/**
 * このスレッドが "実行中のVMのルート" を渡します.
 * このメソッドは通常スクリプトの開始時に一度だけ呼び出されます。
 * スレッドからVMを参照できる必要があるので用意されています。
 * ここから参照されるVMはガベージコレクションの対象になります。
 * @param self
 * @param frame_ref 呼び出し側で開放してください.
 */
void bc_SetScriptThreadFrameRef(bc_ScriptThread* self,
                                struct bc_Frame* frame_ref);

/**
 * このスレッドが "実行中のVMのルート" を返します.
 * @param self
 * @return
 */
struct bc_Frame* bc_GetScriptThreadFrameRef(bc_ScriptThread* self);

/**
 * このスレッドからVMを参照出来ないようにします.
 * 通常、このスレッドに設定されたVMを開放したあとに呼び出します。
 * @param self
 */
void bc_ReleaseScriptThreadFrameRef(bc_ScriptThread* self);

/**
 * メインスレッドを返します.
 * @return
 */
bc_ScriptThread* bc_GetMainScriptThread();

/**
 * メインスレッドの呼び出しコンテキストを返します.
 * @return
 */
struct bc_CallContext* bc_GetScriptThreadContext();

/**
 * メインスレッドを終了します.
 */
void bc_DestroyScriptThread();
#endif  // SIGNAL_THREAD_THREAD_H
