//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_library_interface.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_bc_LIBRARY_INTERFACE_H
#define BEACON_LIB_bc_LIBRARY_INTERFACE_H
//ネイティブメソッドの初期化を行う実装でインクルード出来ます。
#include "beacon/lang/bc_object.h"
#include "beacon/lang/bc_int.h"
#include "beacon/lang/bc_long.h"
#include "beacon/lang/bc_double.h"
#include "beacon/lang/bc_char.h"
#include "beacon/lang/bc_string.h"
#include "beacon/lang/bc_bool.h"
#include "beacon/lang/bc_void.h"
#include "beacon/lang/bc_console.h"
#include "beacon/lang/array.h"
#include "beacon/lang/bc_null.h"
#include "beacon/lang/bc_exception.h"
#include "beacon/lang/unsafe/bc_file.h"
#include "beacon/lang/unsafe/bc_system.h"
#include "beacon/lang/unsafe/bc_locale.h"
#include "beacon/lang/unsafe/bc_time.h"
#endif // !SIGNAL_LIB_bc_LIBRARY_INTERFACE_H
