// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_library_interface.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_bc_LIBRARY_INTERFACE_H
#define BEACON_LIB_bc_LIBRARY_INTERFACE_H
//ネイティブメソッドの初期化を行う実装でインクルード出来ます。
#include "beacon/lang/array.h"
#include "beacon/lang/bool.h"
#include "beacon/lang/char.h"
#include "beacon/lang/console.h"
#include "beacon/lang/double.h"
#include "beacon/lang/exception.h"
#include "beacon/lang/int.h"
#include "beacon/lang/long.h"
#include "beacon/lang/null.h"
#include "beacon/lang/object.h"
#include "beacon/lang/string.h"
#include "beacon/lang/unsafe/file.h"
#include "beacon/lang/unsafe/locale.h"
#include "beacon/lang/unsafe/system.h"
#include "beacon/lang/unsafe/time.h"
#include "beacon/lang/void.h"
#endif  // !SIGNAL_LIB_bc_LIBRARY_INTERFACE_H
