//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_invoke_static_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_IL_FACTOR_INVOKE_STATIC_H
#define BEACON_IL_IL_FACTOR_INVOKE_STATIC_H
#include "../../il_factor_interface.h"
#include "../../../env/fqcn_cache.h"
#include "../../../util/string_pool.h"
struct Enviroment;
struct bc_GenericType;
struct bc_Method;

typedef struct ILInvokeStatic {
	StringView Name;
	bc_FQCNCache* FQCN;
	Vector* Arguments;
	Vector* TypeArgs;
	struct bc_Method* Method;
	int Index;
	struct bc_GenericType* Resolved;
} ILInvokeStatic;

ILInvokeStatic* NewILInvokeStatic(StringView namev);

void GenerateILInvokeStatic(ILInvokeStatic* self, Enviroment* env, CallContext* cctx);

void LoadILInvokeStatic(ILInvokeStatic * self, Enviroment * env, CallContext* cctx);

struct bc_GenericType* EvalILInvokeStatic(ILInvokeStatic * self, Enviroment * env, CallContext* cctx);

char* ILInvokeStaticToString(ILInvokeStatic* self, Enviroment* env);

void DeleteILInvokeStatic(ILInvokeStatic* self);
#endif