//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file subscript_descriptor.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_FACTOR_INVOKE_SUBSCRIPT_DESCRIPTOR_H
#define BEACON_IL_FACTOR_INVOKE_SUBSCRIPT_DESCRIPTOR_H

struct bc_OperatorOverload;
struct bc_SymbolEntry;
struct bc_Field;
struct bc_Property;

typedef enum bc_SubscriptTag {
	SUBSCRIPT_LOCAL_T,
	SUBSCRIPT_FIELD_T,
	SUBSCRIPT_PROPERTY_T,
	SUBSCRIPT_UNDEFINED_T
} bc_SubscriptTag;

typedef struct bc_SubscriptDescriptor {
	bc_SubscriptTag Tag;
	struct bc_OperatorOverload* Operator;
	int Index;
	union {
		struct bc_SymbolEntry* Local;
		struct bc_Field* Field;
		struct bc_Property* Property;
	} Kind;
} bc_SubscriptDescriptor;

struct bc_GenericType* bc_GetSubscriptReceiver(const bc_SubscriptDescriptor* desc);
#endif