//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file subscript_descriptor.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_FACTOR_INVOKE_SUBSCRIPT_DESCRIPTOR_H
#define BEACON_IL_FACTOR_INVOKE_SUBSCRIPT_DESCRIPTOR_H

struct bc_OperatorOverload;
struct bc_SymbolEntry;
struct bc_Field;
struct bc_Property;

typedef enum SubscriptTag {
	SUBSCRIPT_LOCAL_T,
	SUBSCRIPT_FIELD_T,
	SUBSCRIPT_PROPERTY_T,
	SUBSCRIPT_UNDEFINED_T
} SubscriptTag;

typedef struct SubscriptDescriptor {
	SubscriptTag Tag;
	struct bc_OperatorOverload* Operator;
	int Index;
	union {
		struct bc_SymbolEntry* Local;
		struct bc_Field* Field;
		struct bc_Property* Property;
	} Kind;
} SubscriptDescriptor;

struct bc_GenericType* GetSubscriptReceiver(const SubscriptDescriptor* desc);
#endif