//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_compare_op_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_FACTOR_BINARY_IL_FACTOR_COMPARE_OP_IMPL_H
#define BEACON_IL_FACTOR_BINARY_IL_FACTOR_COMPARE_OP_IMPL_H
#include "../../../ast/operator_type.h"
#include "../../call_context.h"
struct bc_ILBinaryOp;
struct bc_GenericType;
struct bc_Enviroment;
typedef struct bc_ILCompareOp {
	struct bc_ILBinaryOp* Parent;
	bc_OperatorType Type;
	int OperatorIndex;
} bc_ILCompareOp;

bc_ILCompareOp* bc_NewILCompareOp(bc_OperatorType type);

struct bc_GenericType* bc_EvalILCompareOp(bc_ILCompareOp * self, struct bc_Enviroment * env, bc_CallContext* cctx);

void bc_GenerateILCompareOp(bc_ILCompareOp* self, struct bc_Enviroment* env, bc_CallContext* cctx);

void bc_LoadILCompareOp(bc_ILCompareOp* self, struct bc_Enviroment* env, bc_CallContext* cctx);

void bc_DeleteILCompareOp(bc_ILCompareOp* self);

char* bc_ILCompareOpToString(bc_ILCompareOp* self, struct bc_Enviroment* env);
#endif