//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_excor_op_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_FACTOR_UNARY_IL_FACTOR_EXCOP_OP_IMPL_H
#define BEACON_IL_FACTOR_UNARY_IL_FACTOR_EXCOP_OP_IMPL_H
#include "../../../ast/operator_type.h"
#include "../../call_context.h"
struct ILBinaryOp;
struct bc_GenericType;
struct bc_Enviroment;

typedef struct ILExcorOp {
	struct ILBinaryOp* Parent;
	bc_OperatorType Type;
	int OperatorIndex;
} ILExcorOp;

ILExcorOp* NewILExcorOp(bc_OperatorType type);

struct bc_GenericType* EvalILExcorOp(ILExcorOp * self, struct bc_Enviroment * env, CallContext* cctx);

void GenerateILExcorOp(ILExcorOp* self, struct bc_Enviroment* env, CallContext* cctx);

void LoadILExcorOp(ILExcorOp* self, struct bc_Enviroment* env, CallContext* cctx);

void DeleteILExcorOp(ILExcorOp* self);

char* ILExcorOpToString(ILExcorOp* self, struct bc_Enviroment* env);
#endif