//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_argument.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_ARGUMENT_H
#define BEACON_IL_IL_ARGUMENT_H
#include "il_factor_interface.h"
/**
 * 実引数を表す要素.
 */
typedef struct bc_ILArgument {
	//char* name;
	bc_ILFactor* Factor;
} bc_ILArgument;

/**
 * 実引数を表す要素を作成します.
 * @return
 */
bc_ILArgument* bc_NewILArgument();

/**
 * 実引数を表す要素を開放します.
 * @param self
 */
void bc_DeleteILArgument(bc_ILArgument* self);
#endif // !SIGNAL_IL_IL_ARGUMENT_H
