//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_constructor_chain.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_CONSTRUCTOR_CHAIN_H
#define BEACON_IL_IL_CONSTRUCTOR_CHAIN_H
#include "../util/vector.h"
#include "../ast/constructor_chain_type.h"
struct bc_Constructor;
/**
 * コンストラクタの連鎖を表す要素.
 */
typedef struct bc_ILConstructorChain {
	bc_ConstructorChainType Type;
	bc_Vector* Arguments;
	struct bc_Constructor* Constructor;
	int ConstructorIndex;
} bc_ILConstructorChain;
/**
 * コンストラクタの連鎖を表す要素を作成します.
 * @return
 */
bc_ILConstructorChain* bc_NewILConstructorChain();

/**
 * コンストラクタの連鎖を表す要素を開放します.
 * @param self
 */
void bc_DeleteILConstructorChain(bc_ILConstructorChain* self);
#endif // !SIGNAL_IL_IL_CONSTRUCTOR_CHAIN_H
