// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_constructor.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_CONSTRUCTOR_H
#define BEACON_IL_IL_CONSTRUCTOR_H
#include "../ast/access_level.h"
#include "../ast/modifier_type.h"
#include "../env/fqcn_cache.h"
#include "../util/vector.h"
struct bc_ILConstructorChain;
/**
 * コンストラクタを表す要素.
 */
typedef struct bc_ILConstructor {
        bc_Vector* Parameters;
        bc_Vector* Statements;
        struct bc_ILConstructorChain* Chain;
        bc_AccessLevel Access;
} bc_ILConstructor;

/**
 * コンストラクタを表す要素を作成します.
 * @return
 */
bc_ILConstructor* bc_NewILConstructor();

/**
 * コンストラクタを表す要素を開放します.
 * @param self
 */
void bc_DeleteILConstructor(bc_ILConstructor* self);
#endif  // !SIGNAL_IL_IL_CONSTRUCTOR_H
