// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_function.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_FUNCTION_H
#define BEACON_IL_IL_FUNCTION_H
#include "../util/string_pool.h"
#include "../util/vector.h"

struct bc_GenericCache;
/**
 * 関数宣言を表す要素.
 */
typedef struct bc_ILFunction {
        bc_StringView Name;
        bc_Vector* TypeParameters;
        bc_Vector* Parameters;
        bc_Vector* Statements;
        struct bc_GenericCache* ReturnGCache;
} bc_ILFunction;

/**
 * 新しい関数宣言を作成します.
 * @param name
 * @return
 */
bc_ILFunction* bc_NewILFunction(bc_StringView name);

/**
 * 関数を解放します.
 * @param self
 */
void bc_DeleteILFunction(bc_ILFunction* self);
#endif  // !SIGNAL_IL_IL_FUNCTION_H
