//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_import.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_IL_IMPORT_H
#define BEACON_IL_IL_IMPORT_H
#include "../util/string_pool.h"
/**
 * インポート宣言を表す要素.
 */
typedef struct ILImport {
	bc_StringView Path;
} ILImport;

/**
 * 指定のパスをインポートするインポート宣言を作成します.
 * 引数は呼び出し側で解放してください。
 * @param path
 * @return
 */
ILImport* NewILImport(bc_StringView path);

/**
 * このインポート宣言と包含された文字列を解放します.
 * @param self
 */
void DeleteILImport(ILImport* self);
#endif // !SIGNAL_IL_IL_IMPORT_H
