//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_stmt_interface.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_STMT_INTERFACE_H
#define BEACON_IL_IL_STMT_INTERFACE_H
#include "../vm/enviroment.h"
#include "../error.h"
#include "call_context.h"
#include <stdint.h>
/**
 * 文の種類を表す列挙型.
 */
typedef enum bc_ILStatementTag {
	ILSTMT_PROC_T,
	ILSTMT_IF_T,
	ILSTMT_WHILE_T,
	ILSTMT_VARIABLE_DECL_T,
	ILSTMT_VARIABLE_INIT_T,
	ILSTMT_RETURN_T,
	ILSTMT_RETURN_EMPTY_T,
	ILSTMT_BREAK_T,
	ILSTMT_CONTINUE_T,
	ILSTMT_INFERENCED_TYPE_INIT_T,
	ILSTMT_TRY_T,
	ILSTMT_THROW_T,
	ILSTMT_ASSERT_T,
	ILSTMT_DEFER_T,
	ILSTMT_YIELD_RETURN_T,
	ILSTMT_YIELD_BREAK_T,
	ILSTMT_INJECT_JNI_T,
} bc_ILStatementTag;

//詳細は il_stmt_impl.h を参照してください。
struct bc_ILProc;
struct bc_ILIf;
struct bc_ILWhile;
struct bc_ILVariableDecl;
struct bc_ILVariableInit;
struct bc_ILReturn;
typedef void* ILReturnEmpty;
struct bc_ILInferencedTypeInit;
struct bc_ILTry;
struct bc_ILThrow;
struct bc_ILAssert;
struct bc_ILDefer;
struct bc_ILYieldReturn;
typedef void* ILStatementYieldBreak;
struct bc_ILInjectJNI;

/**
 * 文を表す要素です.
 */
typedef struct bc_ILStatement {
	bc_ILStatementTag Type;
	int Lineno;
	union {
		struct bc_ILProc* Proc;
		struct bc_ILIf* If;
		struct bc_ILWhile* While;
		struct bc_ILVariableDecl* VariableDecl;
		struct bc_ILVariableInit* VariableInit;
		struct bc_ILReturn* Return;
		ILReturnEmpty ReturnEmpty;
		struct bc_ILInferencedTypeInit* InferencedTypeInit;
		struct bc_ILTry* Try;
		struct bc_ILThrow* Throw;
		struct bc_ILAssert* Assert;
		struct bc_ILDefer* Defer;
		struct bc_ILYieldReturn* YieldReturn;
		ILStatementYieldBreak YieldBreak;
		struct bc_ILInjectJNI* InjectJNI;
	} Kind;
} bc_ILStatement;

#define bc_NewILStatement(type) (bc_MallocILStmt(type, __FILE__, __LINE__))
bc_ILStatement* bc_MallocILStmt(bc_ILStatementTag type, const char* filename, int lineno);

/**
 * 文を生成します.
 * @param self
 * @param env
 * @param cctx
 */
void bc_GenerateILStmt(bc_ILStatement* self, bc_Enviroment* env, bc_CallContext* cctx);

/**
 * ステートメントを読み込んでエラーがあれば記録します.
 * @param self
 * @param env
 * @param cctx
 */
void bc_LoadILStmt(bc_ILStatement * self, bc_Enviroment* env, bc_CallContext* cctx);

/**
 * 文を開放します.
 * @param self
 */
void bc_DeleteILStmt(bc_ILStatement* self);
#endif // !SIGNAL_IL_IL_STMT_INTERFACE_H
