// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_type_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_TYPE_IMPL_H
#define BEACON_IL_IL_TYPE_IMPL_H

#include "type/il_class_impl.h"
#include "type/il_enum_impl.h"
#include "type/il_interface_impl.h"
#endif  // !SIGNAL_IL_IL_TYPE_IMPL_H
