// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file class_loader_ilload_type_module_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#ifndef BEACON_ENV_CLL_CLASS_LOADER_MODULE_H
#define BEACON_ENV_CLL_CLASS_LOADER_MODULE_H
#include "../../util/vector.h"
//このファイルは非公開ヘッダーか .c からのみインクルードして下さい。
struct bc_AST;
struct bc_FQCNCache;
struct bc_GenericCache;
struct bc_ClassLoader;

void CLILFQCNCache(struct bc_AST* afqcn, struct bc_FQCNCache* fqcn);

void CLILGenericCache(struct bc_AST* afqcn, struct bc_GenericCache* dest);

/**
 * 型名の一覧を dst へ出力します.
 * @param self
 * @param dst
 * @param typename_list
 */
void CLILTypenameList(struct bc_ClassLoader* self, bc_Vector* dst,
                      struct bc_AST* atypename_list);

void CLILTypeParameter(struct bc_ClassLoader* self, struct bc_AST* asource,
                       bc_Vector* dest);

void CLILTypeArgument(struct bc_ClassLoader* self, struct bc_AST* atype_args,
                      bc_Vector* dest);

void CLILParameterList(struct bc_ClassLoader* self, bc_Vector* list,
                       struct bc_AST* asource);

void CLILArgumentList(struct bc_ClassLoader* self, bc_Vector* list,
                      struct bc_AST* asource);
#endif