//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_system.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_LIB_BEACON_BEACON_UNSAFE_BC_SYSTEM_H
#define BEACON_LIB_BEACON_BEACON_UNSAFE_BC_SYSTEM_H
/**
 * created by rbtools/rnative.rb
 * time: 2018-08-17
 */
struct Type;

void InitBCSystem();

struct Type* GetBCSystemType();

#endif
