//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_time.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_LIB_BEACON_LANG_UNSAFE_BC_TIME_H
#define BEACON_LIB_BEACON_LANG_UNSAFE_BC_TIME_H
struct Type;

void InitBCTime();

struct Type* GetBCTimeType();
#endif