//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file time.h
 * @brief 時間に関する低レベルなラッパーです。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_LIB_BEACON_LANG_UNSAFE_BC_TIME_H
#define BEACON_LIB_BEACON_LANG_UNSAFE_BC_TIME_H
struct bc_Type;

/**
 * beacon::unsafe::Timeクラスを初期化します。
 */
void bc_InitTime();

/**
 * beacon::unsafe::Timeクラスを返します。
 * @return
 */
struct bc_Type* bc_GetTimeType();
#endif