//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file generate.h
 * @brief オペコードの生成を簡単にするための関数を定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_VM_GENERATE_H
#define BEACON_VM_GENERATE_H
#include "opcode_buf.h"
#include "../env/field.h"
#include "../env/method.h"
#include "../env/property.h"

/**
 * フィールドを取得するオペコードを生成します.
 * @param buf
 * @param fi
 * @param index
 */
void GenerateGetField(OpcodeBuf* buf, bc_Field* fi, int index);

/**
 * プロパティを取得するオペコードを生成します.
 * @param buf
 * @param prop
 * @param index
 */
void GenerateGetProperty(OpcodeBuf* buf, bc_Property* prop, int index);

/**
 * フィールドに代入するオペコードを生成します.
 * @param buf
 * @param fi
 * @param index
 */
void GeneratePutField(OpcodeBuf* buf, bc_Field* fi, int index);
/**
 * プロパティに代入するオペコードを生成します.
 * @param buf
 * @param fi
 * @param index
 */
void GeneratePutProperty(OpcodeBuf* buf, bc_Property* prop, int index);
#endif