//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file symbol_table.h
 * @brief ローカル変数と添字の変換テーブルを定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_VM_SYMBOL_TABLE_H
#define BEACON_VM_SYMBOL_TABLE_H
#include "../util/tree_map.h"
#include "../util/numeric_map.h"
#include "../util/string_pool.h"
#include <stdio.h>
#include <stdbool.h>
//#include "../env/class.h"
struct bc_GenericType;
struct bc_SymbolEntry;
/**
 * 変数名とインデックスの変換テーブルです.
 * オペコードの中では、添え字で変数アクセスを行います。
 */
typedef struct bc_SymbolTable {
	NumericMap* VariableMap;
	int Count;
	int ScopeDepth;
} bc_SymbolTable;

/**
 * シンボルテーブルを作成します.
 * @return
 */
bc_SymbolTable* bc_NewSymbolTable();

/**
 * 指定の名前に対応するインデックスを返します.
 * もしくは、既に登録されているならそれを返します。
 * @param self
 * @param gtp
 * @param namev
 * @return nameに対応するエントリが存在せず、clsがNULLならNULL
 */
struct bc_SymbolEntry* bc_EntrySymbolTable(bc_SymbolTable* self, struct bc_GenericType* gtp, StringView namev);

/**
 * 既に指定の名前が含まれるなら true.
 * @param self
 * @param namev
 * @return
 */
bool bc_IsContainsSymbol(bc_SymbolTable* self, StringView namev);

/**
 * シンボルテーブルをダンプします.
 * @param self
 */
void bc_DumpSymbolTable(bc_SymbolTable* self);

/**
 * シンボルテーブルを開放します.
 * @param self
 */
void bc_DeleteSymbolTable(bc_SymbolTable* self);
#endif // !SIGNAL_VM_SYMBOL_TABLE_H
