// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file vm_trace.h
 * @brief 実行中のVMの状態を保存する構造体を定義します。
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_VM_TRACE_H
#define BEACON_VM_TRACE_H
#include <stdint.h>
struct bc_Frame;
/**
 * 実行中のVMの実行位置を保存する構造体.
 */
typedef struct bc_VMTrace {
        struct bc_Frame* SnapShot;
        int PC;
        int JumpLevel;
} bc_VMTrace;

/**
 * 指定のVMでトレースを作成します.
 * @param v
 * @return
 */
bc_VMTrace* bc_NewVMTrace(struct bc_Frame* snapShot);

/**
 * トレースを解放します.
 * @param self
 */
void bc_DeleteVMTrace(bc_VMTrace* self);
#endif  // !SIGNAL_VM_TRACE_H
