//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file yield_context.h
 * @brief 'yield return'が実行された時点でのコンテキストを保存する構造体を定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_VM_YIELD_CONTEXT_H
#define BEACON_VM_YIELD_CONTEXT_H
#include "../util/vector.h"
struct Object;

typedef struct YieldContext {
	Vector* BackupVariableTable;
	Vector* BackupValueStack;
	Vector* VariableTable;
	Vector* ValueStack;
	Vector* Parameters;
	struct Object* Source;
	struct Object* Stock;
	bool IsCached;
	int YieldCount;
	int YieldOffset;
	int Length;
} YieldContext;

#define NewYieldContext() (MallocYieldContext(__FILE__, __LINE__))
YieldContext* MallocYieldContext(const char* filename, int lineno);

void ClearBackupYieldContext(YieldContext* self);

void DeleteYieldContext(YieldContext* self);
#endif