// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file bc_library_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_LIB_SG_LIBRARY_IMPL_H
#define BEACON_LIB_SG_LIBRARY_IMPL_H
//ネイティブメソッド自体を実装する .c からインクルード出来ます。
#include "../env/method.h"
#include "../env/namespace.h"
#include "../env/object.h"
#include "../env/script_context.h"
#include "../env/type/class_impl.h"
#include "../env/type_interface.h"

#include "../util/mem.h"
#include "../util/string_pool.h"

#include "../vm/enviroment.h"
#include "../vm/opcode_buf.h"
#include "../vm/vm.h"
#endif  // !SIGNAL_LIB_SG_LIBRARY_IMPL_H
