// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file meta_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_ENV_META_H
#define BEACON_ENV_META_H
//クラス自体の実装に関わるメタ関数
#include "../../il/call_context.h"
#include "../../util/string_pool.h"
#include "../../util/vector.h"
#include "../../vm/enviroment.h"
#include "../constructor.h"
#include "../method.h"
#include "../operator_overload.h"
#include "resolve.h"
struct bc_Type;
struct bc_Class;
struct bc_Constructor;

#endif  // !SIGNAL_ENV_META_H
