/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_koya_jbeacon_ScriptContext */

#ifndef _Included_jp_koya_jbeacon_ScriptContext
#define _Included_jp_koya_jbeacon_ScriptContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_koya_jbeacon_ScriptContext
 * Method:    nativeOpen
 * Signature: ()Ljp/koya/jbeacon/ScriptContext;
 */
JNIEXPORT jobject JNICALL Java_jp_koya_jbeacon_ScriptContext_nativeOpen
  (JNIEnv *, jclass);

/*
 * Class:     jp_koya_jbeacon_ScriptContext
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_koya_jbeacon_ScriptContext_nativeClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
