//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file jp_koya_jbeacon_Beacon.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_koya_jbeacon_Beacon */

#ifndef _Included_jp_koya_jbeacon_Beacon
#define _Included_jp_koya_jbeacon_Beacon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_koya_jbeacon_Beacon
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_koya_jbeacon_Beacon_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     jp_koya_jbeacon_Beacon
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_koya_jbeacon_Beacon_nativeDestroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
