/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_koya_jbeacon_BCEval */

#ifndef _Included_jp_koya_jbeacon_BCEval
#define _Included_jp_koya_jbeacon_BCEval
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_koya_jbeacon_BCEval
 * Method:    nativeFile
 * Signature: (Ljava/lang/String;)Ljp/koya/jbeacon/SymbolTable;
 */
JNIEXPORT jobject JNICALL Java_jp_koya_jbeacon_BCEval_nativeFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_koya_jbeacon_BCEval
 * Method:    nativeString
 * Signature: (Ljava/lang/String;)Ljp/koya/jbeacon/SymbolTable;
 */
JNIEXPORT jobject JNICALL Java_jp_koya_jbeacon_BCEval_nativeString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
