// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file jp_koya_jbeacon_BCEval.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_koya_jbeacon_BCEval */

#ifndef _Included_jp_koya_jbeacon_BCEval
#define _Included_jp_koya_jbeacon_BCEval
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_koya_jbeacon_BCEval
 * Method:    nativeFile
 * Signature:
 * (Ljava/lang/String;Ljp/koya/jbeacon/SymbolTable;)Ljp/koya/jbeacon/SymbolTable;
 */
JNIEXPORT jobject JNICALL Java_jp_koya_jbeacon_BCEval_nativeFile(JNIEnv *,
                                                                 jclass,
                                                                 jstring,
                                                                 jobject);

/*
 * Class:     jp_koya_jbeacon_BCEval
 * Method:    nativeString
 * Signature:
 * (Ljava/lang/String;Ljp/koya/jbeacon/SymbolTable;)Ljp/koya/jbeacon/SymbolTable;
 */
JNIEXPORT jobject JNICALL Java_jp_koya_jbeacon_BCEval_nativeString(JNIEnv *,
                                                                   jclass,
                                                                   jstring,
                                                                   jobject);

#ifdef __cplusplus
}
#endif
#endif
