/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_koya_jbeacon_Namespace */

#ifndef _Included_jp_koya_jbeacon_Namespace
#define _Included_jp_koya_jbeacon_Namespace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_koya_jbeacon_Namespace
 * Method:    nativeGetNamespace
 * Signature: (Ljava/lang/String;)Ljp/koya/jbeacon/Namespace;
 */
JNIEXPORT jobject JNICALL Java_jp_koya_jbeacon_Namespace_nativeGetNamespace
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
