// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file file_entry.h
 * @brief ファイルひとつあたりの情報を定義します。
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#ifndef BEACON_UTIL_FILE_ENTRY_H
#define BEACON_UTIL_FILE_ENTRY_H
#include <stdbool.h>
/**
 * ファイルを表す構造体.
 * フルパスを表します。
 */
typedef struct bc_FileEntry {
        char* FileName;
        bool IsFile;
} bc_FileEntry;

/**
 * 文字列を複製して新しいエントリを作成します.
 * @param filename
 * @return
 */
bc_FileEntry* bc_NewFileEntry(const char* filename);

/**
 * 文字列を参照して新しいエントリを作成します.
 * @param filename DeleteFileEntry によって解放されます。
 * @return
 */
bc_FileEntry* bc_RefFileEntry(char* filename);

/**
 * エントリを解放します.
 * @param self
 */
void bc_DeleteFileEntry(bc_FileEntry* self);
#endif
