//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_enum_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_ENUM_H
#define BEACON_IL_IL_ENUM_H
#include "../../util/vector.h"
#include "../../util/string_pool.h"
#include "../il_type_interface.h"

typedef struct bc_ILEnum {
	bc_StringView Name;
	bc_Vector* Items;
} bc_ILEnum;

bc_ILType* bc_WrapILEnum(bc_ILEnum* self);

bc_ILEnum* bc_NewILEnum(bc_StringView namev);

void bc_DeleteILEnum(bc_ILEnum* self);
#endif // !SIGNAL_IL_IL_ENUM_H
