//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_enum_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_ENUM_H
#define BEACON_IL_IL_ENUM_H
#include "../../util/vector.h"
#include "../../util/string_pool.h"
#include "../il_type_interface.h"

typedef struct ILEnum {
	bc_StringView Name;
	bc_Vector* Items;
} ILEnum;

bc_ILType* WrapILEnum(ILEnum* self);

ILEnum* NewILEnum(bc_StringView namev);

void DeleteILEnum(ILEnum* self);
#endif // !SIGNAL_IL_IL_ENUM_H
