//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_interface_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_INTERFACE_H
#define BEACON_IL_IL_INTERFACE_H
#include "../../util/vector.h"
#include "../../util/string_pool.h"
#include "../il_type_interface.h"
struct ILMethod;
/**
 * インターフェースを表す要素.
 */
typedef struct ILInterface {
	bc_StringView Name;
	bc_Vector* Methods;
	bc_Vector* Extends;
	bc_Vector* TypeParameters;
	bc_Vector* Properties;
} ILInterface;

/**
 * 型をスーパーセットにラップします.
 * @param self
 * @return
 */
ILType* WrapILInterface(ILInterface* self);

/**
 * インターフェースを作成します.
 * @param namev
 * @return
 */
ILInterface* NewILInterface(bc_StringView namev);

/**
 * プロパティを追加します.
 * @param self
 * @param prop
 */
void AddPropertyILInterface(ILInterface* self, struct ILProperty* prop);

/**
 * プロパティを追加します.
 * @param self
 * @param method
 */
void AddMethodILInterface(ILInterface* self, struct ILMethod* method);

/**
 * インターフェースを開放します.
 * @param self
 */
void DeleteILInterface(ILInterface* self);
#endif // !SIGNAL_IL_IL_INTERFACE_H
