//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file assign_operator_type.h
 * @brief 代入演算子の種類を定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_AST_ASSIGN_OPERATOR_TYPE_H
#define BEACON_AST_ASSIGN_OPERATOR_TYPE_H
/**
 * 代入演算子の種類.
 */
typedef enum bc_AssignOperatorType {
	ASSIGN_OTYPE_DEF_T,
	ASSIGN_OTYPE_ADD_T,
	ASSIGN_OTYPE_SUB_T,
	ASSIGN_OTYPE_MUL_T,
	ASSIGN_OTYPE_DIV_T,
	ASSIGN_OTYPE_MOD_T,
} bc_AssignOperatorType;
#endif // !SIGNAL_AST_ASSIGN_OPERATOR_TYPE_H
