//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file ast_new_literal.h
 * @brief リテラルを表すAST要素の生成関数を定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_AST_AST_NEW_LITERAL_H
#define BEACON_AST_AST_NEW_LITERAL_H
#include "ast.h"

/**
 * 整数型の値を保存する要素を作成します.
 * @param i
 */
AST* NewASTInt(int i);

/**
 * 実数型の値を保存する要素を作成します.
 * @param d
 */
AST* NewASTDouble(double d);

/**
 * 文字を保存する要素を作成します.
 * @param ch
 * @return
 */
AST* NewASTChar(char ch);

/**
 * 文字を保存する要素を作成します.
 * @param str
 * @return
 */
AST* NewASTString(StringView str);
#endif // !SIGNAL_AST_AST_NEW_LITERAL_H
