//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file ast_new_operator.h
 * @brief 演算子による計算可能なAST要素の生成関数を定義します。
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_AST_AST_NEW_OPERATOR_H
#define BEACON_AST_AST_NEW_OPERATOR_H
#include "ast.h"
#include "assign_operator_type.h"
//typedef struct ast { } ast;

/**
 * 単項演算子を表す要素を作成します.
 * @param tag
 * @param a
 * @return
 */
bc_AST* NewASTUnary(bc_ASTTag tag, bc_AST* a);

/**
 * 二項演算子を表す要素を作成します.
 * @param tag
 * @param aleft
 * @param aright
 * @return
 */
bc_AST* NewASTBinary(bc_ASTTag tag, bc_AST* aleft, bc_AST* aright);
#endif // !SIGNAL_AST_AST_NEW_OPERATOR_H
