//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_explicit_unary_op_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_FACTOR_IL_FACTOR_EXPLICIT_UNARY_OP_IMPL_H
#define BEACON_IL_FACTOR_IL_FACTOR_EXPLICIT_UNARY_OP_IMPL_H
#include "../../ast/operator_type.h"
#include "../call_context.h"
struct ILFactor;
struct bc_Enviroment;
struct bc_GenericType;

typedef struct ILExplicitUnaryOp {
	struct ILFactor* Receiver;
	bc_OperatorType Type;
	int Index;
} ILExplicitUnaryOp;

struct ILFactor* WrapILExplicitUnaryOp(ILExplicitUnaryOp* self);

ILExplicitUnaryOp* NewILExplicitUnaryOp(bc_OperatorType type);

void GenerateILExplicitUnaryOp(ILExplicitUnaryOp* self, struct bc_Enviroment* env, CallContext* cctx);

void LoadILExplicitUnaryOp(ILExplicitUnaryOp* self, struct bc_Enviroment* env, CallContext* cctx);

struct bc_GenericType* EvalILExplicitUnaryOp(ILExplicitUnaryOp* self, struct bc_Enviroment* env, CallContext* cctx);

void DeleteILExplicitUnaryOp(ILExplicitUnaryOp* self);
#endif