//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_string_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_FACTOR_STRING_H
#define BEACON_IL_IL_FACTOR_STRING_H
#include "../il_factor_interface.h"
#include "../../util/string_pool.h"

//struct opcode_buf;
/**
 * 文字列を表す要素.
 */
typedef struct ILString {
	bc_StringView Value;
} ILString;

ILFactor* WrapILString(ILString* self);

ILString* NewILString(bc_StringView valuev);

void GenerateILString(ILString* self, bc_Enviroment* env, CallContext* cctx);

void LoadILString(ILString* self, bc_Enviroment* env, CallContext* cctx);

bc_GenericType* EvalILString(ILString* self, bc_Enviroment* env, CallContext* cctx);

char* ILStringToString(ILString* self, bc_Enviroment* env);

void DeleteILString(ILString* self);

#endif // !SIGNAL_IL_IL_FACTOR_STRING_H
