// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_bool_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_FACTOR_BOOL_H
#define BEACON_IL_IL_FACTOR_BOOL_H
#include <stdbool.h>
#include "../il_factor_interface.h"

struct bc_Enviroment;
struct bc_Type;
/**
 * boolリテラルを表す要素.
 */
typedef struct bc_ILBool {
        bool Value;
} bc_ILBool;

bc_ILFactor* bc_WrapILBool(bc_ILBool* self);

bc_ILBool* bc_NewILBool(bool b);

void bc_GenerateILBool(bc_ILBool* self, bc_Enviroment* env,
                       bc_CallContext* cctx);

bc_GenericType* bc_EvalILBool(bc_ILBool* self, bc_Enviroment* env,
                              bc_CallContext* cctx);

char* bc_ILBoolToString(bc_ILBool* self, bc_Enviroment* env);

void bc_DeleteILBool(bc_ILBool* self);

#endif  // !SIGNAL_IL_IL_FACTOR_BOOL_H
