//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_binary_op_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_FACTOR_BINARY_OP_H
#define BEACON_IL_IL_FACTOR_BINARY_OP_H
#include "../il_factor_interface.h"
#include "../../ast/operator_type.h"
#include <stdbool.h>

struct ILArithmeticOp;
struct ILLogicOp;
struct ILCompareOp;
struct ILShiftOp;
struct ILExcorOp;

/**
 * 二項演算子を表す要素.
 */
typedef struct bc_ILBinaryOp {
	bc_OperatorType Type;
	bc_OperatorCategory Category;
	bc_ILFactor* Left;
	bc_ILFactor* Right;
	bool IsLoaded;
	union {
		struct ILArithmeticOp* ArithmeticOp;
		struct ILLogicOp* LogicOp;
		struct ILCompareOp* CompareOp;
		struct ILShiftOp* ShiftOp;
		struct ILExcorOp* ExcorOp;
	} Kind;
} bc_ILBinaryOp;

bc_ILFactor* bc_WrapILBinaryOp(bc_ILBinaryOp* self);

bc_ILBinaryOp* bc_NewILBinaryOp(bc_OperatorType type);

void bc_GenerateILBinaryOp(bc_ILBinaryOp* self, bc_Enviroment* env, bc_CallContext* cctx);

void bc_LoadILBinaryOp(bc_ILBinaryOp* self, bc_Enviroment* env, bc_CallContext* cctx);

bc_GenericType* bc_EvalILBinaryOp(bc_ILBinaryOp* self, bc_Enviroment* env, bc_CallContext* cctx);

char* bc_ILBinaryOpToString(bc_ILBinaryOp* self, bc_Enviroment* env);

void bc_DeleteILBinaryOp(bc_ILBinaryOp* self);

char* bc_ILBinaryOpToStringSimple(bc_ILBinaryOp* self, bc_Enviroment* env);

bool bc_IsIntIntBinaryOp(bc_ILBinaryOp* self, bc_Enviroment* env, bc_CallContext* cctx);

bool bc_IsDoubleDoubleBinaryOp(bc_ILBinaryOp* self, bc_Enviroment* env, bc_CallContext* cctx);

bool bc_IsBoolBoolBinaryOp(bc_ILBinaryOp* self, bc_Enviroment* env, bc_CallContext* cctx);

bool bc_IsCharCharBinaryOp(bc_ILBinaryOp* self, bc_Enviroment* env, bc_CallContext* cctx);

int bc_GetIndexILBinaryOp(bc_ILBinaryOp* self, bc_Enviroment* env, bc_CallContext* cctx);

int bc_GetIndexILBinaryOp2(bc_ILFactor* receiver, bc_ILFactor* arg, bc_OperatorType otype, bc_Enviroment* env, bc_CallContext* cctx);

bc_GenericType* bc_ApplyILBinaryOp(bc_ILBinaryOp* self, bc_GenericType* gtype, bc_Enviroment* env, bc_CallContext* cctx);
#endif // !SIGNAL_IL_IL_FACTOR_BINARY_OP_H
