//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_double_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_IL_IL_FACTOR_DOUBLE_H
#define BEACON_IL_IL_FACTOR_DOUBLE_H
#include "../il_factor_interface.h"

//struct opcode_buf;
/**
 * 浮動小数リテラルを表す要素.
 */
typedef struct bc_ILDouble {
	double Value;
} bc_ILDouble;

bc_ILFactor* bc_WrapILDouble(bc_ILDouble* self);

bc_ILDouble* bc_NewILDouble(double d);

void bc_GenerateILDouble(bc_ILDouble* self, bc_Enviroment* env, bc_CallContext* cctx);

void bc_LoadILDouble(bc_ILDouble* self, bc_Enviroment* env, bc_CallContext* cctx);

bc_GenericType* bc_EvalILDouble(bc_ILDouble* self, bc_Enviroment* env, bc_CallContext* cctx);

char* bc_ILDoubleToString(bc_ILDouble* self, bc_Enviroment* env);

void bc_DeleteILDouble(bc_ILDouble* self);

#endif // !SIGNAL_IL_IL_FACTOR_DOUBLE_H
