// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file il_factor_assign_op_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#ifndef BEACON_IL_IL_FACTOR_ASSIGN_OP_IMPL_H
#define BEACON_IL_IL_FACTOR_ASSIGN_OP_IMPL_H
#include "../il_factor_interface.h"
struct bc_GenericType;
typedef struct bc_ILAssignOp {
        bc_ILFactor* Left;
        bc_ILFactor* Right;
} bc_ILAssignOp;

bc_ILFactor* bc_WrapILAssignOp(bc_ILAssignOp* self);

bc_ILAssignOp* bc_NewILAssignOp();

void bc_LoadILAssignOp(bc_ILAssignOp* self, bc_Enviroment* env,
                       bc_CallContext* cctx);

void bc_GenerateILAssignOp(bc_ILAssignOp* self, bc_Enviroment* env,
                           bc_CallContext* cctx);

struct bc_GenericType* bc_EvalILAssignOp(bc_ILAssignOp* self,
                                         bc_Enviroment* env,
                                         bc_CallContext* cctx);

void bc_DeleteILAssignOp(bc_ILAssignOp* self);
#endif