//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file class_loader_link_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_ENV_CLL_LINK_IMPL_H
#define BEACON_ENV_CLL_LINK_IMPL_H
#include "../class_loader.h"

/**
 * 指定のクラスローダーをリンクします.
 * @param self
 * @param type
 */
void LinkClassLoader(bc_ClassLoader* self, LinkType type);
#endif