//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file class_loader_bcload_import_module_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_ENV_CLL_CLASS_LOADER_BCLOAD_IMPORT_MODULE_IMPL_H
#define BEACON_ENV_CLL_CLASS_LOADER_BCLOAD_IMPORT_MODULE_IMPL_H
#include "../class_loader.h"

/**
 * インポートの一覧を確認して、読み込むべきファイルがあるなら読み込みます.
 * @param self
 * @param ilimports
 */
void CLBC_import(bc_ClassLoader* self, bc_Vector* ilimports);
/**
 * selfを親として fullPath のファイルを読み込みます.
 * @param self
 * @param fullPath
 */
void CLBC_new_load(bc_ClassLoader* self, char* fullPath);

/**
 * fullPathをロードするためのローダを作成して返します.
 * @param self
 * @param fullPath
 * @return
 */
bc_ClassLoader* CLBC_import_new(bc_ClassLoader* self, char* fullPath);
#endif