//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file class_loader_bcload_member_module_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#ifndef BEACON_ENV_CLL_CLASS_LOADER_BCLOAD_MEMBER_MODULE_IMPL_H
#define BEACON_ENV_CLL_CLASS_LOADER_BCLOAD_MEMBER_MODULE_IMPL_H
#include "../class_loader.h"
#include "../../il/il_type_interface.h"
#include "../../il/il_field.h"
#include "../../il/il_property.h"
#include "../../il/il_method.h"
#include "../../il/il_operator_overload.h"
#include "../../il/call_context.h"
#include "../../il/il_constructor.h"
#include "../../env/type_interface.h"
#include "../../env/namespace.h"
#include "../../env/method.h"
#include "../../env/field.h"
#include "../../env/constructor.h"
#include "../../env/operator_overload.h"
#include "../../env/property.h"

bool CLBC_field_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, ILField* ilfi, bc_Namespace* scope, CallContext* cctx);
bool CLBC_field_impl(bc_ClassLoader* self, bc_Type* tp, bc_Field* fi, bc_Namespace* scope, CallContext* cctx);
/**
 * フィールド宣言を読み込んでクラスに追加します.
 * @param self
 * @param iltype
 * @param tp
 * @param ilfields
 */
void CLBC_fields_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, Vector* ilfields, bc_Namespace* scope);
void CLBC_fields_impl(bc_ClassLoader* self, bc_Namespace* scope, bc_Type* tp,Vector* ilfields, Vector* sgfields);

bool CLBC_Property_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, ILProperty* ilprop, bc_Namespace* scope, CallContext* cctx);
bool CLBC_Property_impl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, ILProperty* ilprop, bc_Property* prop, bc_Namespace* scope, CallContext* cctx);

/**
 * @param self
 * @param iltype
 * @param tp
 * @param scope
 */
void CLBC_properties_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, Vector* ilprops, bc_Namespace* scope);
void CLBC_properties_impl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, Vector* ilprops, Vector* sgprops, bc_Namespace* scope);

bool CLBC_method_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, ILMethod* ilmt, bc_Namespace* scope);
bool CLBC_method_impl(bc_ClassLoader* self, bc_Namespace* scope, ILType* iltype, bc_Type* tp, ILMethod* ilmt, bc_Method* mt);

/**
 * メソッド宣言を読み込んでクラスに追加します.
 * @param self
 * @param iltype
 * @param tp
 * @param ilmethods
 * @param scope
 */
void CLBC_methods_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, Vector* ilmethods, bc_Namespace* scope);
void CLBC_methods_impl(bc_ClassLoader* self, bc_Namespace* scope, ILType* iltype, bc_Type* tp, Vector* ilmethods, Vector* sgmethods);


bool CLBC_ctor_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, ILConstructor* ilcons, bc_Namespace* scope);
bool CLBC_ctor_impl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, ILConstructor* ilcons, bc_Constructor* cons, bc_Namespace* scope);

/**
 * コンストラクタ宣言を読み込んでクラスに追加します.
 * @param self
 * @param iltype
 * @param tp
 * @param scope
 */
void CLBC_ctors_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, bc_Namespace* scope);
void CLBC_ctors_impl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp);

bool CLBC_operator_overload_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, ILOperatorOverload* ilopov, bc_Namespace* scope);
bool CLBC_operator_overload_impl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, ILOperatorOverload* ilopov, bc_OperatorOverload* opov, bc_Namespace* scope);

void CLBC_operator_overloads_decl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, bc_Namespace* scope);
void CLBC_operator_overloads_impl(bc_ClassLoader* self, ILType* iltype, bc_Type* tp, bc_Namespace* scope);

bool CLBC_corutine(bc_ClassLoader* self, bc_Method* mt, bc_Enviroment* env, Vector* ilparams, Vector* ilstmts, CallContext* cctx, bc_Namespace* range);

void CLBC_body(bc_ClassLoader* self, Vector* stmt_list, bc_Enviroment* dest, CallContext* cctx, bc_Namespace* range);
#endif