// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file class_loader_ilload_impl.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#ifndef BEACON_ENV_CLASS_LOADER_ILLOAD_IMPL_H
#define BEACON_ENV_CLASS_LOADER_ILLOAD_IMPL_H
//このヘッダーは class_loader.h 以外からはインクルードしないでください。
#include "../../il/il_factor_impl.h"
#include "../../il/il_namespace.h"
#include "../../il/il_stmt_impl.h"
#include "../class_loader.h"
#include "../generic_cache.h"

/**
 * ASTの全てのエントリを IL に変換します.
 * @param self
 * @param source_code
 */
void ILLoadClassLoader(bc_ClassLoader* self, bc_AST* source_code);

#endif
