// BEGIN-AUTOGENERATED-BLOCK
/**
 * @file cl.h
 * @brief コマンドラインから実行される関数を定義します。
 * @author koya
 * @date 2018/10/31
 */
// END-AUTOGENERATED-BLOCK

#ifndef BEACON_CL_H
#define BEACON_CL_H

/**
 * 全てのテストを実行します.
 * @param argc
 * @param argv
 * @return
 */
int bc_TestCmd(int argc, char* argv[]);

/**
 * ASTをダンプします.
 * @param filename
 * @return
 */
int bc_DumpASTCmd(const char* filename);

/**
 * ASTをダンプします.
 * @param filename
 * @return
 */
int bc_DumpILCmd(const char* filename);

/**
 * オペコードをダンプします.
 * @param filename
 * @return
 */
int bc_DumpOpCodeCmd(const char* filename);

/**
 * 指定のファイルを実行します.
 * @param filename
 * @return
 */
int bc_RunCmd(const char* filename);
#endif