//BEGIN-AUTOGENERATED-BLOCK
/**
 * @file test.h
 * @brief ここに概要を記述します
 * @author koya
 * @date 2018/10/31
 */
//END-AUTOGENERATED-BLOCK

#pragma once
#ifndef BEACON_TEST_H
#define BEACON_TEST_H
#include <stdbool.h>

int bc_RunTest();

bool bc_IsTestNow();
#endif // !SIGNAL_TEST_H
